# Generated by Django 3.1.3 on 2021-05-03 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(help_text='Church Name', max_length=120, verbose_name='Church Name')),
                ('church_brief_description', tinymce.models.HTMLField(blank=True, help_text='Brief discription', verbose_name='Brief discription')),
                ('church_image', models.ImageField(blank=True, help_text='Profile Image', null=True, upload_to='church_images', verbose_name='Profile image')),
                ('church_address', models.CharField(help_text='Address', max_length=255, verbose_name='Address')),
                ('church_url', models.CharField(blank=True, default='', help_text='Website adress', max_length=100, verbose_name='Web adress')),
                ('church_phone', models.CharField(blank=True, default='', help_text='Phone number', max_length=15, verbose_name='Phone number')),
                ('church_email', models.CharField(blank=True, default='', help_text='Email address', max_length=50, verbose_name='Email')),
                ('church_notice_on_map', tinymce.models.HTMLField(blank=True, default='', help_text='Brief inform on map', verbose_name='Brief inform on map')),
                ('church_lon', models.FloatField(blank=True, default=0.0, help_text='Churchs longtitue acorrding Google', null=True, verbose_name='Churchs longtitue')),
                ('church_lat', models.FloatField(blank=True, default=0.0, help_text='Churchs latitue acorrding Google', null=True, verbose_name='Churchs latitue')),
                ('church_geo_hash', models.CharField(blank=True, default='', max_length=30, verbose_name='geo_hash')),
                ('church_update_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Last updated date', verbose_name='Last updated date')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchChapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_chapel_name', models.CharField(help_text='Chapel name', max_length=50, verbose_name='Chapel name')),
                ('church_chapel_discrible', tinymce.models.HTMLField(help_text='Chapel discription', verbose_name='Chapel discription')),
                ('church_chapel_total_seats', models.SmallIntegerField(default=1, help_text='Chapel total seats capable', verbose_name='Chapel total seats')),
                ('church_chapel_church', models.ForeignKey(help_text='Select Church', on_delete=django.db.models.deletion.CASCADE, to='adminapp.church')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Country name', max_length=50, verbose_name='Name')),
                ('country_code', models.CharField(help_text='Country code', max_length=12, verbose_name='Postal code')),
                ('country_en_name', models.CharField(help_text='International Name', max_length=50, verbose_name='International Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(help_text='District name', max_length=50, verbose_name='Name')),
                ('district_code', models.CharField(help_text='Postal code', max_length=12, verbose_name='Postal code')),
                ('district_en_name', models.CharField(help_text='International Name', max_length=50, verbose_name='International Name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(help_text='Ngôn ngữ của Quốc gia', max_length=50, verbose_name='Tên Ngôn ngữ')),
                ('language_code', models.CharField(help_text='Mã theo i18n', max_length=3, verbose_name='Mã')),
                ('language_en_name', models.CharField(help_text='Tên theo tiếng anh', max_length=50, verbose_name='Tên quốc tế')),
                ('language_flag_small_url', models.ImageField(blank=True, help_text='Hình ảnh minh hoạ', null=True, upload_to='flags', verbose_name='Hình ảnh')),
                ('language_flag_medium_url', models.ImageField(blank=True, help_text='Hình ảnh minh hoạ', null=True, upload_to='flags', verbose_name='Hình ảnh')),
            ],
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_date', models.DateField(help_text='Ngày diễn ra Thánh Lễ', verbose_name='Ngày')),
                ('mass_time', models.TimeField(help_text='thời gian', verbose_name='Giờ')),
                ('mass_title', models.CharField(help_text='Tiêu đề của sự kiện', max_length=50, verbose_name='Chủ đề')),
                ('mass_language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ')),
                ('mass_date_ordinary', models.CharField(help_text='Tuần phụng vụ', max_length=3, verbose_name='Tuần phụng vụ')),
                ('mass_VietcatholicJP_celebrant', models.CharField(blank=True, help_text='Cha chủ tế', max_length=40, null=True, verbose_name='Cha chủ tế')),
                ('mass_slots', models.SmallIntegerField(default=0, help_text='Số chỗ', verbose_name='Số chỗ')),
                ('mass_slots_registered', models.SmallIntegerField(blank=True, default=0, help_text='Số người đăng ký', null=True, verbose_name='Số đăng ký')),
                ('mass_slots_attended', models.SmallIntegerField(blank=True, default=0, help_text='Số người tham dự', null=True, verbose_name='Số tham dự')),
                ('mass_waiting', models.SmallIntegerField(blank=True, default=0, help_text='Số người đang đợi', null=True, verbose_name='Số người đang đợi')),
                ('mass_total_registered', models.SmallIntegerField(blank=True, default=0, help_text='Tổng số người đăng ký', null=True, verbose_name='Tổng số đăng ký')),
                ('mass_online_url', models.URLField(blank=True, help_text='Link trực tuyến', null=True, verbose_name='Link trực tuyến')),
                ('mass_image', models.ImageField(blank=True, help_text='Hình ảnh minh hoạ', null=True, upload_to='mass_images', verbose_name='Hình ảnh')),
                ('mass_last_updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Lần cuối cập nhật', null=True, verbose_name='Ngày cập nhật')),
                ('mass_active', models.BooleanField(blank=True, default=True, help_text='Tình trạng', null=True, verbose_name='Tình trạng')),
                ('mass_waiting_flag', models.BooleanField(blank=True, default=False, help_text='Cho phép đăng ký đợi', null=True, verbose_name='Cho phép đăng ký ')),
                ('mass_church', models.ForeignKey(blank=True, help_text='chọn Nhà thờ', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.church')),
                ('mass_church_chapel', models.ForeignKey(blank=True, help_text='chọn Nhà thờ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.churchchapel')),
                ('mass_created_user', models.ForeignKey(blank=True, help_text='Người cuối cập nhật', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_week_day', models.CharField(choices=[('0', 'Thứ hai'), ('1', 'Thứ ba'), ('2', 'Thứ tư'), ('3', 'Thứ năm'), ('4', 'Thứ sáu'), ('5', 'Thứ bảy'), ('6', 'Chúa Nhật')], help_text='Ngày trong tuần ra Thánh Lễ (0-6)', max_length=10, verbose_name='Ngày trong tuần')),
                ('mass_time', models.TimeField(help_text='thời gian', verbose_name='Giờ')),
                ('mass_schedule_chapel', models.ForeignKey(help_text='Select Church', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.churchchapel')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(help_text='Province name', max_length=50, verbose_name='Name')),
                ('province_code', models.CharField(help_text='Postal code', max_length=12, verbose_name='Postal code')),
                ('province_en_name', models.CharField(help_text='International Name', max_length=50, verbose_name='International Name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(help_text='Số ghế', max_length=4, null=True, verbose_name='Số ghế')),
                ('seat_type', models.CharField(choices=[('', 'Select'), ('20', 'Over 20'), ('35', 'Over 35'), ('55', 'Over 55'), ('priority', 'Priority Seat')], help_text='Kiểu ghế', max_length=30, verbose_name='Kiểu ghế')),
                ('seat_status', models.CharField(choices=[('A', 'Availabel'), ('T', 'Taken'), ('U', 'Unavailabel')], default='A', help_text='Chọn tình trạng', max_length=2, verbose_name='Tình trạng')),
                ('seat_mass_schedule', models.ForeignKey(blank=True, default=None, help_text='Mass chapel schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.massschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('registration_user_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('registration_user_age', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('registration_confirm_code', models.CharField(blank=True, default='', max_length=25)),
                ('registration_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('registration_total_seats', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('registration_status', models.CharField(blank=True, choices=[('W', 'Waiting'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'Presented'), ('AB', 'Absented'), ('C', 'Cancel')], default='W', max_length=3, null=True)),
                ('registration_approve_status', models.CharField(blank=True, choices=[('W', 'Waiting'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'Presented'), ('AB', 'Absented'), ('C', 'Cancel')], default='A', help_text='Trạng thái được cập nhập sau khi đăng ký', max_length=3, null=True)),
                ('registration_last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('registration_confirm_status', models.CharField(blank=True, choices=[('CF', 'CONFIRMED'), ('NF', 'NOTCONFIRM')], default='NC', max_length=3, null=True)),
                ('registration_last_update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Thời gian cập nhập lần cuối bởi quản lý', null=True)),
                ('registration_last_updated_user', models.ForeignKey(blank=True, default=None, help_text='Người cuối cập nhật', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_last_updated_user', to=settings.AUTH_USER_MODEL)),
                ('registration_mass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.mass')),
                ('registration_seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seat')),
                ('registration_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_time_title', models.CharField(blank=True, help_text='Tiêu đề', max_length=255, null=True, verbose_name='Tiêu đề')),
                ('mass_time_start', models.DateTimeField(blank=True, help_text='Thời điểm bắt đầu', null=True, verbose_name='Thời gian')),
                ('mass_time_end', models.DateTimeField(blank=True, help_text='Thời điểm kết thúc', null=True, verbose_name='Thời gian')),
                ('mass_time_type', models.CharField(choices=[('NORMAL', 'Weekday'), ('SUNDAY', 'Sunday'), ('SPECIAL', 'Special'), ('Ceremony', 'Ceremony'), ('OTHER', 'Others')], default='NORMAL', help_text='Kiểu Thánh Lễ', max_length=15, verbose_name='Mass type')),
                ('mass_time_date_ordinary', models.CharField(default='0', help_text='Tuần phụng vụ', max_length=4, verbose_name='Tuần Phụng vụ')),
                ('mass_time_last_updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('mass_time_church', models.ForeignKey(help_text='Tên nhà thờ', on_delete=django.db.models.deletion.CASCADE, to='adminapp.church')),
                ('mass_time_created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mass_time_language', models.ForeignKey(help_text='Ngôn ngữ', on_delete=django.db.models.deletion.CASCADE, to='adminapp.language')),
                ('mass_time_updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_time_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mass',
            name='mass_schedule',
            field=models.ForeignKey(help_text='Lựa chọn lịch xếp Lễ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.massschedule'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(help_text='Ngày tháng', verbose_name='Ngày tháng')),
                ('event_time', models.TimeField(help_text='thời gian diễn ra sự kiện', verbose_name='Giờ')),
                ('event_time_length', models.SmallIntegerField(blank=True, default=1, help_text='Khoảng thời gian diễn ra sự kiện', verbose_name='Khoảng thời gian')),
                ('event_title', models.CharField(help_text='Tiêu đề của sự kiện', max_length=100, verbose_name='Chủ đề')),
                ('event_content', tinymce.models.HTMLField(blank=True, help_text='Nội dung của sự kiện', verbose_name='Nội dung')),
                ('event_language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ')),
                ('event_date_ordinary', models.CharField(help_text='Tuần phụng vụ', max_length=10, verbose_name='Tuần phụng vụ')),
                ('event_holder', models.CharField(help_text='Người tổ chức', max_length=40, verbose_name='Người tổ chức')),
                ('event_slots', models.SmallIntegerField(default=125, help_text='Tổng số ghế', verbose_name='Tổng số ghế')),
                ('event_slots_registered', models.SmallIntegerField(default=0, help_text='Số người đã đăng ký', verbose_name='Số người đăng ký')),
                ('event_attended', models.SmallIntegerField(default=0, help_text='Số người tham dự', verbose_name='Số người tham dự')),
                ('event_waiting', models.SmallIntegerField(default=0, help_text='Số người đang đợi', verbose_name='Số người đang đợi')),
                ('event_online_url', models.URLField(blank=True, help_text='Url trực tuyến', verbose_name='Url trực tuyến')),
                ('event_image', models.ImageField(blank=True, help_text='Hình ảnh', null=True, upload_to='mass_images', verbose_name='Hình ảnh')),
                ('event_active', models.BooleanField(default=True, help_text='Tình trạng sự kiện', verbose_name='Tình trạng')),
                ('event_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày tạo', verbose_name='Ngày tạo')),
                ('event_last_updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày cập nhật', verbose_name='Ngày cập nhật')),
                ('event_waiting_flag', models.BooleanField(default=False, help_text='Cho phép đăng ký đợi', verbose_name='Cho phép đăng ký ')),
                ('event_created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_post_title', models.CharField(help_text='Post title max length = 120', max_length=120, verbose_name='Post title')),
                ('church_post_image', models.ImageField(blank=True, help_text='Image for the title', null=True, upload_to='church_images', verbose_name='Image')),
                ('church_post_type', models.CharField(help_text='Type of this post', max_length=120, verbose_name='Post type')),
                ('church_post_content', tinymce.models.HTMLField(default='', help_text='Content', verbose_name='Content')),
                ('church_post_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Posted date', verbose_name='Posted date')),
                ('church_post_update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated date')),
                ('church_post_like', models.IntegerField(default=0, help_text='Number of post liked', verbose_name='Post like')),
                ('church_post_share', models.IntegerField(default=0, help_text='Number of post shared', verbose_name='Posted Shared')),
                ('church_post_clicked', models.IntegerField(default=0, help_text='Viewed numbers', verbose_name='View numbers')),
                ('church_post_status', models.BooleanField(blank=True, default=True, help_text='Approve status', null=True, verbose_name='Status')),
                ('church_post_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.church', verbose_name='Belong to Church')),
                ('church_post_update_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_post_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Last updated User')),
                ('church_post_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_post_user', to=settings.AUTH_USER_MODEL, verbose_name='Posted User')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_image_title', models.CharField(help_text='Brief discription for the image', max_length=120, verbose_name='Image title')),
                ('church_image', models.ImageField(blank=True, help_text='Hình ảnh đại diện', null=True, upload_to='church_images', verbose_name='Hình ảnh')),
                ('church_image_like', models.IntegerField(default=0, help_text='Number of post liked', verbose_name='Post like')),
                ('church_image_share', models.IntegerField(default=0, help_text='Number of post shared', verbose_name='Posted Shared')),
                ('church_image_clicked', models.IntegerField(default=0, help_text='View numbers', verbose_name='View numbers')),
                ('church_image_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.church')),
                ('church_image_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UpLoaded User')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchChapelSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapel_seat_no', models.CharField(help_text='Số ghế', max_length=4, verbose_name='Số ghế')),
                ('chapel_seat_type', models.CharField(choices=[('', 'Select'), ('20', 'Over 20'), ('35', 'Over 35'), ('55', 'Over 55'), ('priority', 'Priority Seat')], help_text='Kiểu ghế', max_length=30, verbose_name='Kiểu ghế')),
                ('chapel_seat_chapel', models.ForeignKey(help_text='Select Church', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.churchchapel')),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='church_country',
            field=models.ForeignKey(blank=True, help_text='Belong to country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_reversed', to='adminapp.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='church',
            name='church_district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_reversed', to='adminapp.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='church',
            name='church_language_main',
            field=models.ForeignKey(help_text='Main Language', on_delete=django.db.models.deletion.CASCADE, related_name='Church_language', to='adminapp.language'),
        ),
        migrations.AddField(
            model_name='church',
            name='church_province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_reversed', to='adminapp.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='church',
            name='church_register_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AddField(
            model_name='church',
            name='church_update_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Last updated User'),
        ),
    ]
