# Generated by Django 3.1.3 on 2021-05-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210503_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
