# Generated by Django 3.1.3 on 2021-05-04 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_first_name', models.CharField(default='', help_text='Họ', max_length=30, verbose_name='Họ')),
                ('profile_last_name', models.CharField(default='', help_text='Tên', max_length=30, verbose_name='Tên')),
                ('profile_full_name', models.CharField(default='', help_text='Họ tên đầy đủ', max_length=30, verbose_name='Họ Tên')),
                ('profile_image', models.ImageField(default='default.JPG', help_text='Không bắt buộc', upload_to='profile_pics', verbose_name='Hình đại diện')),
                ('profile_address', models.CharField(default='', help_text='Xin nhập địa chỉ hiện tại của bạn', max_length=300, verbose_name='Địa chỉ')),
                ('profile_age', models.SmallIntegerField(default=0, help_text='Xin nhập độ tuổi của bạn', verbose_name='Tuổi')),
                ('profile_phone_number', models.CharField(blank=True, default='', help_text='Xin nhập số điện thoại để liên lạc khi cần', max_length=12, verbose_name='Số điện thoại')),
                ('profile_language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', help_text='Ngôn ngữ sử dụng trên trang web', max_length=15, verbose_name='Ngôn ngữ')),
                ('profile_access_num', models.IntegerField(default=0, help_text='Số lần truy cập trang web', verbose_name='Số lần truy cập')),
                ('profile_reading_num', models.IntegerField(default=0, help_text='Số lần đọc kinh thánh', verbose_name='Số lần đọc')),
                ('profile_health_status', models.CharField(choices=[('GOOD', 'Tốt'), ('NORM', 'Bình thường'), ('NGOOD', 'Không khoẻ lắm'), ('SICK', 'Bị ốm gần đây')], default='GOOD', help_text='Tình trạng sức khoẻ của bạn hiện tại', max_length=15, verbose_name='Tình trạng')),
                ('profile_last_check_tempture', models.SmallIntegerField(default=36, help_text='Nhiệt độ cơ thể lần kiểm tra gần nhất', verbose_name='Nhiệt độ cơ thể')),
                ('profile_last_check_tempture_time', models.DateField(default=django.utils.timezone.now, help_text='Ngày kiểm tra nhiệt độ', verbose_name='Kiểm tra ngày')),
                ('profile_last_update_time', models.DateField(default=django.utils.timezone.now, help_text='Lần cuối truy cập', verbose_name='Lần cuối truy cập')),
                ('profile_account_confimred', models.BooleanField(default=False, help_text='Tình trạng xác minh', verbose_name='Xác minh')),
                ('profile_code', models.CharField(blank=True, default='', help_text='Mã xác nhận', max_length=20, verbose_name='Mã xác nhận')),
                ('profile_home_count', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('profile_registered_count', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('profile_gospel_count', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('profile_absented_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('profile_presented_count', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('profile_user__username', 'profile_user__email'),
                'unique_together': {('profile_user', 'profile_full_name', 'profile_address')},
            },
        ),
    ]
