# Generated by Django 3.1.3 on 2021-05-04 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf_title', models.CharField(help_text='Tiêu đề của sự kiện', max_length=100, verbose_name='Chủ đề')),
                ('nf_type', models.CharField(choices=[('Mass', 'Mass'), ('Event', 'Event'), ('Inform', 'Inform'), ('News', 'News')], help_text='Bài viết liên quan đến thể loại gì', max_length=15, verbose_name='Thể loại')),
                ('nf_image', models.ImageField(blank=True, help_text='Hình ảnh', null=True, upload_to='post_images', verbose_name='Hình ảnh')),
                ('nf_brief_content', tinymce.models.HTMLField(help_text='Nội dung tóm tắt', verbose_name='Tóm tắt')),
                ('nf_content', tinymce.models.HTMLField(help_text='Nội dung', verbose_name='Nội dung')),
                ('nf_language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ')),
                ('nf_date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày tạo', verbose_name='Ngày tạo')),
                ('nf_date_approved', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày chấp nhận', verbose_name='Ngày chấp nhận')),
                ('nf_date_edited', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày cuối sửa đổi', verbose_name='Ngày sửa')),
                ('nf_post_like', models.IntegerField(default=0, help_text='Number of post liked', verbose_name='Post like')),
                ('nf_post_share', models.IntegerField(default=0, help_text='Number of post shared', verbose_name='Posted Shared')),
                ('nf_post_clicked', models.IntegerField(default=0, help_text='Viewed numbers', verbose_name='View numbers')),
                ('nf_priority_level', models.CharField(choices=[('0', 'Very Importance'), ('1', 'Importance'), ('2', 'Normal'), ('3', 'Rejected')], help_text='Mức độ ưu tiên của bài viết', max_length=2, verbose_name='Độ ưu tiên')),
                ('nf_status', models.CharField(choices=[('E', 'Editing'), ('W', 'Waiting'), ('A', 'Approved'), ('R', 'Rejected')], help_text='Tình trạng của bài viết', max_length=10, verbose_name='Tình trạng')),
                ('nf_post_status', models.BooleanField(blank=True, default=True, help_text='Approve status', null=True, verbose_name='Status')),
                ('nf_user_approved', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_approved', to=settings.AUTH_USER_MODEL)),
                ('nf_user_created', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_created', to=settings.AUTH_USER_MODEL)),
                ('nf_user_last_edit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Feed',
                'verbose_name_plural': 'New Feeds',
                'ordering': ('nf_date_edited',),
            },
        ),
        migrations.CreateModel(
            name='DailyGospel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_gospel_title', models.CharField(help_text='Chủ đề của ngày ', max_length=50, verbose_name='Chủ đề')),
                ('daily_gospel_date', models.DateField(help_text='Ngày tháng dương lịch', verbose_name='Ngày tháng')),
                ('daily_gospel_date_ordinary', models.CharField(help_text='Tuần phụng vụ', max_length=3, verbose_name='Tuần phụng vụ')),
                ('daily_gosspel_content', tinymce.models.HTMLField(blank=True, default='', help_text='Lời Chúa Nội dung', null=True, verbose_name='Nội dung')),
                ('daily_gospel_readed', models.IntegerField(default=0, help_text='Số lượt đọc', verbose_name='Số lượt đọc')),
                ('daily_gospel_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày tạo', verbose_name='Ngày viết')),
                ('daily_gospel_last_updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Lần cuối cập nhật', verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(blank=True, default=True, help_text='Approve status', null=True, verbose_name='Status')),
                ('daily_gospel_created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('daily_gospel_laguage', models.ForeignKey(help_text='Ngôn ngữ chính', on_delete=django.db.models.deletion.CASCADE, to='adminapp.language')),
            ],
        ),
    ]
