# Generated by Django 3.1.3 on 2021-05-04 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0005_dailygospel_newfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='mass_VietcatholicJP_celebrant',
        ),
        migrations.AddField(
            model_name='churchpost',
            name='church_post_language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.ForeignKey(blank=True, help_text='Nơi tổ chức', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.church'),
        ),
        migrations.AddField(
            model_name='mass',
            name='mass_father_celebrant',
            field=models.ForeignKey(blank=True, help_text='Cha chủ tế', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_father', to=settings.AUTH_USER_MODEL, verbose_name='Cha chủ tế'),
        ),
        migrations.AddField(
            model_name='mass',
            name='mass_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.dailygospel'),
        ),
        migrations.AlterField(
            model_name='church',
            name='church_language_main',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', help_text='Ngôn ngữ sử dụng trên trang web', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='dailygospel',
            name='daily_gospel_laguage',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='mass_created_user',
            field=models.ForeignKey(blank=True, help_text='Người cuối cập nhật', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mass',
            name='mass_total_registered',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Tổng số người đăng ký bao gồm cả người huỷ', null=True, verbose_name='Tổng số đăng ký'),
        ),
        migrations.AlterField(
            model_name='masstime',
            name='mass_time_language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='newfeed',
            name='nf_type',
            field=models.CharField(choices=[('letter', 'Letter'), ('Refl', 'Gospel Reflection'), ('Event', 'Event'), ('Inform', 'Inform'), ('News', 'News')], help_text='Bài viết liên quan đến thể loại gì', max_length=15, verbose_name='Thể loại'),
        ),
    ]
