# Generated by Django 3.1.3 on 2021-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20210504_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygospel',
            old_name='status',
            new_name='daily_gospel_status',
        ),
        migrations.RenameField(
            model_name='masstime',
            old_name='mass_time_start',
            new_name='mass_date',
        ),
        migrations.RenameField(
            model_name='masstime',
            old_name='mass_time_end',
            new_name='mass_time',
        ),
        migrations.AddField(
            model_name='dailygospel',
            name='daily_gospel_clicked',
            field=models.IntegerField(default=0, help_text='Viewed numbers', verbose_name='View numbers'),
        ),
        migrations.AddField(
            model_name='dailygospel',
            name='daily_gospel_like',
            field=models.IntegerField(default=0, help_text='Number of post liked', verbose_name='Post like'),
        ),
        migrations.AddField(
            model_name='dailygospel',
            name='daily_gospel_share',
            field=models.IntegerField(default=0, help_text='Number of post shared', verbose_name='Posted Shared'),
        ),
        migrations.AddField(
            model_name='mass',
            name='mass_require_flag',
            field=models.BooleanField(blank=True, default=True, help_text='Yêu cầu đăng', null=True, verbose_name='Yêu cầu đăng ký '),
        ),
        migrations.AddField(
            model_name='masstime',
            name='mass_time_status',
            field=models.BooleanField(blank=True, default=True, help_text='Approve status', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='church',
            name='church_language_main',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], default='vi', help_text='Ngôn ngữ sử dụng trên trang web', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='churchchapelseat',
            name='chapel_seat_type',
            field=models.CharField(choices=[('20', 'Over 20'), ('32', 'Over 32'), ('50', 'Over 50'), ('Pr', 'Priority Seat')], help_text='Kiểu ghế', max_length=30, verbose_name='Kiểu ghế'),
        ),
        migrations.AlterField(
            model_name='churchpost',
            name='church_post_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='dailygospel',
            name='daily_gospel_laguage',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='mass_active',
            field=models.BooleanField(blank=True, default=True, help_text='Cho phép đăng ký', null=True, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='mass_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='masstime',
            name='mass_time_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], default='vi', help_text='Ngôn ngữ sử dụng', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_confirm_status',
            field=models.CharField(blank=True, choices=[('CF', 'confirmed'), ('NC', 'not confirmed yet')], default='NC', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('A', 'Availabel'), ('R', 'Registered'), ('T', 'Taken'), ('U', 'Unavailabel')], default='A', help_text='Chọn tình trạng', max_length=2, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('20', 'Over 20'), ('32', 'Over 32'), ('50', 'Over 50'), ('Pr', 'Priority Seat')], help_text='Kiểu ghế', max_length=30, verbose_name='Kiểu ghế'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], default='vi', help_text='Ngôn ngữ sử dụng trên trang web', max_length=15, verbose_name='Ngôn ngữ'),
        ),
    ]
