# Generated by Django 3.1.3 on 2021-05-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20210505_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchpost',
            options={'ordering': ('church_post_date',), 'verbose_name': 'ChurchPost', 'verbose_name_plural': 'Church List Post'},
        ),
        migrations.AlterField(
            model_name='church',
            name='church_language_main',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='newfeed',
            name='nf_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語'), ('vi', 'Tiếng Việt'), ('es', 'Spanish')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seat'),
        ),
    ]
