# Generated by Django 3.1.3 on 2021-05-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20210505_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masstime',
            options={'ordering': ('mass_date',), 'verbose_name': 'MassTime', 'verbose_name_plural': 'MassTime'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-registration_date',), 'verbose_name': 'Registration', 'verbose_name_plural': 'Registration'},
        ),
    ]
