# Generated by Django 3.1.3 on 2021-05-03 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_full_name', models.CharField(default='', help_text='Họ tên đầy đủ', max_length=30, verbose_name='Họ Tên')),
                ('contact_email', models.CharField(help_text='Xin nhập địa chỉ email', max_length=100, verbose_name='Email')),
                ('contact_content', models.TextField(help_text='Nội dung liên hệ', verbose_name='Nội dung')),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Xin nhập số điện thoại để liên lạc khi cần', max_length=12, verbose_name='Số điện thoại')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày liên hệ', verbose_name='Ngày liên hệ')),
                ('contact_reply_status', models.BooleanField(default=False, help_text='Trạng thái phản hồi', verbose_name='Trạng thái')),
                ('contact_reply_content', models.TextField(default='', help_text='Nội dung phản hồi', verbose_name='Nội dung phản hồi')),
            ],
        ),
        migrations.CreateModel(
            name='NewFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf_title', models.CharField(help_text='Tiêu đề của sự kiện', max_length=100, verbose_name='Chủ đề')),
                ('nf_type', models.CharField(choices=[('Mass', 'Mass'), ('Event', 'Event'), ('Inform', 'Inform'), ('News', 'News')], help_text='Bài viết liên quan đến thể loại gì', max_length=15, verbose_name='Thể loại')),
                ('nf_image', models.ImageField(blank=True, help_text='Hình ảnh', null=True, upload_to='post_images', verbose_name='Hình ảnh')),
                ('nf_brief_content', tinymce.models.HTMLField(help_text='Nội dung tóm tắt', verbose_name='Tóm tắt')),
                ('nf_content', tinymce.models.HTMLField(help_text='Nội dung', verbose_name='Nội dung')),
                ('nf_language', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('es', 'Spanish'), ('vi', 'Tiếng Việt')], help_text='Ngôn ngữ', max_length=15, verbose_name='Ngôn ngữ')),
                ('nf_date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày tạo', verbose_name='Ngày tạo')),
                ('nf_date_approved', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày chấp nhận', verbose_name='Ngày chấp nhận')),
                ('nf_date_edited', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày cuối sửa đổi', verbose_name='Ngày sửa')),
                ('nf_post_like', models.IntegerField(default=0, help_text='Number of post liked', verbose_name='Post like')),
                ('nf_post_share', models.IntegerField(default=0, help_text='Number of post shared', verbose_name='Posted Shared')),
                ('nf_post_clicked', models.IntegerField(default=0, help_text='Viewed numbers', verbose_name='View numbers')),
                ('nf_priority_level', models.CharField(choices=[('0', 'Very Importance'), ('1', 'Importance'), ('2', 'Normal'), ('3', 'Rejected')], help_text='Mức độ ưu tiên của bài viết', max_length=2, verbose_name='Độ ưu tiên')),
                ('nf_status', models.CharField(choices=[('E', 'Editing'), ('W', 'Waiting'), ('A', 'Approved'), ('R', 'Rejected')], help_text='Tình trạng của bài viết', max_length=10, verbose_name='Tình trạng')),
                ('nf_post_status', models.BooleanField(blank=True, default=True, help_text='Approve status', null=True, verbose_name='Status')),
                ('nf_user_approved', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_approved', to=settings.AUTH_USER_MODEL)),
                ('nf_user_created', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_created', to=settings.AUTH_USER_MODEL)),
                ('nf_user_last_edit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_user_last_edit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Feed',
                'verbose_name_plural': 'New Feeds',
                'ordering': ('nf_date_edited',),
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_title', models.CharField(max_length=100)),
                ('carousel_url', models.ImageField(blank=True, null=True, upload_to='web_images/carousel')),
                ('carousel_content', models.CharField(max_length=200)),
                ('carousel_active', models.CharField(blank=True, default='', max_length=10)),
                ('carousel_language', models.ForeignKey(blank=True, default=None, help_text='Ngôn ngữ', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=100)),
                ('announcement_url', models.ImageField(blank=True, null=True, upload_to='web_images/announ')),
                ('announcement_content', tinymce.models.HTMLField()),
                ('announcement_active', models.BooleanField(blank=True, default=True)),
                ('announcement_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement_created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('announcement_language', models.ForeignKey(blank=True, default=None, help_text='Ngôn ngữ', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language')),
            ],
            options={
                'ordering': ['announcement_create_date'],
            },
        ),
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus_title', models.CharField(max_length=100)),
                ('aboutus_url', models.ImageField(blank=True, null=True, upload_to='web_images/announ')),
                ('aboutus_content', tinymce.models.HTMLField()),
                ('aboutus_active', models.BooleanField(blank=True, default=True)),
                ('aboutus_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aboutus_created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aboutus_language', models.ForeignKey(blank=True, default=None, help_text='Ngôn ngữ', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language')),
            ],
        ),
    ]
